name: Build Size Report2

on:
  # Note! you can't safely use "pull_request_target" here
  # This workflow is mostly useful for "internal PRs"
  # External PRs won't be able to post a PR comment
  # See https://github.com/preactjs/compressed-size-action/issues/54
  # See https://securitylab.github.com/research/github-actions-preventing-pwn-requests
  pull_request:
    branches:
      - master

jobs:
  report-build-size-diff2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: "build:en"
          pattern: "./packages/core/dist/**/*.{js,css}"
          compression: 'none'
